CLASS z_class_testgit DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

PUBLIC SECTION.
interfaces if_oo_adt_classrun.
PROTECTED SECTION.
PRIVATE SECTION.
ENDCLASS.



CLASS z_class_testgit IMPLEMENTATION.
METHOD IF_OO_ADT_CLASSRUN~MAIN.
OUT->WRITE('HELLO WORLD').
ENDMETHOD.
ENDCLASS.
